#!/usr/bin/env python3
"""Compile audited H8SX row masks and field restrictions to Rust data."""
import argparse
import json
from pathlib import Path
import re
from h8sx_operands import Compiler, SIZES

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true", help="Verify checked-in Rust data without writing")
args = parser.parse_args()

rows = [json.loads(line) for line in Path("spec/h8sx-rows.jsonl").read_text().splitlines()]
entries = []
fields_by_row = []
specs = []
families = {}
family_ids = []
buckets = [[] for _ in range(65536)]
for index, row in enumerate(rows):
    syntax = row.get("inferred_syntax", row["syntax"])
    name = syntax.split()[0]
    length = row["length"]
    padding = 128 - length * 8
    mask = int(row["mask"], 16) << padding
    value = int(row.get("reviewed_value", row["value"]), 16) << padding
    constraints = []
    fields = []
    for token, offset, width in row["fields"]:
        if fields and fields[-1][0] == token and fields[-1][1] + fields[-1][2] == offset:
            fields[-1][2] += width
        else:
            fields.append([token, offset, width])
    for token, offset, width in fields:
        shift = 128 - offset - width
        if token == "d" and width == 2:
            # §1.8.3: short displacement is 1/2/3 times operand size.
            constraints.append((shift, width, 1, 3))
        if token == "x" and width == 3 and name.split(".")[0] in {"ADD", "SUB", "CMP", "MOV", "AND", "OR", "XOR"}:
            # Each arithmetic addressing matrix specifies #x:3(1-7).
            constraints.append((shift, width, 1, 7))
        if token.startswith("rn+"):
            # §2.2.62/94/96: serial register list, no wrapping ER7/ER0.
            constraints.append((shift, width, int(token[-1]), 7))
        if token == "rn" and name == "STM.L":
            group = re.search(r"ERn-ERn\+([123])", syntax)
            assert group
            constraints.append((shift, width, 0, 7-int(group[1])))
        if token == "d" and width in (8, 16) and (
            name in {"BRA", "BRN", "BHI", "BLS", "BCC", "BCS", "BNE", "BEQ",
                     "BVC", "BVS", "BPL", "BMI", "BGE", "BLT", "BGT", "BLE", "BSR"}
            or name in {"BRA/BC", "BRA/BS", "BSR/BC", "BSR/BS"}
        ):
            # §1.8.8 and instruction descriptions: even branch destination.
            mask |= 1 << shift
    assert mask & value == value
    assert len(constraints) <= 2, (syntax, constraints)
    constraints += [(0, 0, 0, 0)] * (2-len(constraints))
    compiler = Compiler(row)
    specs.append(compiler.compile())
    key = (compiler.name, compiler.size)
    if key not in families:
        families[key] = []
    family_ids.append(list(families).index(key))
    families[key].append(index)
    entries.append((mask, value, length, name, constraints))
    fields_by_row.append(fields)
    first_mask, first_value = mask >> 112, value >> 112
    variable = ~first_mask & 65535
    subset = variable
    while True:
        buckets[first_value | subset].append(index)
        if subset == 0:
            break
        subset = (subset-1) & variable

indices = []
offsets = [0]
for bucket in buckets:
    # Short instructions take precedence over longer row prefixes. Aliases
    # keep source order (MOV precedes POP/PUSH), providing a stable choice.
    indices.extend(sorted(bucket, key=lambda i: (entries[i][2], i)))
    offsets.append(len(indices))

out = [
    "// Generated by scripts/compile-h8sx-table.py; do not edit by hand.",
    "// H8SX REJ09B0102 Rev.4 §2.4, with explicit constraints in the generator.",
    "use super::sx_table::{Constraint, Row};",
    "use super::sx_operands::{AddressKind, AddressSpec, Family, Field, Register, Spec, Template};",
    "use super::{Reg, Size};",
    "pub(super) static ROWS: &[Row] = &[",
]
for index, (mask, value, length, name, constraints) in enumerate(entries):
    checks = ",".join(f"Constraint({s},{w},{lo},{hi})" for s,w,lo,hi in constraints)
    out.append(f'Row {{ mask: 0x{mask:032x}, value: 0x{value:032x}, len: {length}, name: "{name}", index: {index}, family: {family_ids[index]}, checks: [{checks}] }}, // row {index}, p.{rows[index]["page"]}')
out.append("];")
for name, kind, values in [("OFFSETS", "u32", offsets), ("INDICES", "u16", indices)]:
    out.append(f"pub(super) static {name}: &[{kind}] = &[")
    for start in range(0, len(values), 24):
        out.append(",".join(map(str, values[start:start+24])) + ",")
    out.append("];")
out.append("pub(super) static SPECS: &[Spec] = &[")
out.extend(spec + "," for spec in specs)
out.append("];")
out.append("pub(super) static FAMILIES: &[Family] = &[")
for (name, size), members in families.items():
    members.sort(key=lambda i: (entries[i][2], i))
    size = f"Some(Size::{SIZES[size]})" if size else "None"
    out.append(f'Family {{ mnemonic: "{name}", size: {size}, rows: &[{",".join(map(str,members))}] }},')
out.append("];")
output = "\n".join(out) + "\n"
destination = Path("src/isa/sx_table_data.rs")
if args.check:
    assert destination.read_text() == output, "Regenerate H8SX runtime data"
else:
    destination.write_text(output)
# Fixed-size records: length byte followed by five 14-byte padded witnesses.
fixtures = bytearray()
for mask, value, length, _, constraints in entries:
    fixtures.append(length)
    for pattern in (0, (1 << 128)-1, 0x0123456789abcdef1032547698badcfe,
                    0xfedcba9876543210efcdab8967452301,
                    0x55aa33cc0ff096693cc35aa5f00f6996):
        input = value | (pattern & ~mask)
        for shift, width, lo, hi in constraints:
            field_mask = ((1 << width)-1) << shift
            number = min(hi, max(lo, (input & field_mask) >> shift))
            input = (input & ~field_mask) | (number << shift)
        fixtures.extend(input.to_bytes(16, "big")[:length].ljust(14, bytes([0])))
fixture = Path("tests/data/sx_rows.bin")
if args.check:
    assert fixture.read_bytes() == fixtures, "Regenerate H8SX row witnesses"
else:
    fixture.parent.mkdir(parents=True, exist_ok=True)
    fixture.write_bytes(fixtures)
print(f"{len(entries)} rows, {len(indices)} first-word candidates")

# Longer-instruction audit: vary each operand field independently through all
# register/small-field values and signed/unsigned extension boundaries.
field_fixtures = bytearray()
for (mask, value, length, _, constraints), fields in zip(entries, fields_by_row):
    if length <= 4:
        continue
    samples = set()
    baseline = value | (0x0123456789abcdef1032547698badcfe & ~mask)
    for _, offset, width in fields:
        shift = 128-offset-width
        maximum = (1 << width)-1
        values = range(maximum+1) if width <= 5 else (
            0, 1, 2, maximum//2, maximum//2+1, maximum//2+2, maximum-1, maximum)
        for number in values:
            sample = (baseline & ~(maximum << shift)) | (number << shift)
            sample = (sample & ~mask) | value
            for cshift, cwidth, lo, hi in constraints:
                cmask = ((1 << cwidth)-1) << cshift
                cnumber = min(hi, max(lo, (sample & cmask) >> cshift))
                sample = (sample & ~cmask) | (cnumber << cshift)
            samples.add(sample)
    for sample in sorted(samples):
        field_fixtures.append(length)
        field_fixtures.extend(sample.to_bytes(16, "big")[:length].ljust(14, bytes([0])))
field_path = Path("tests/data/sx_fields.bin")
if args.check:
    assert field_path.read_bytes() == field_fixtures, "Regenerate H8SX field witnesses"
else:
    field_path.write_bytes(field_fixtures)
print(f"{len(field_fixtures)//15} extended operand-field witnesses")
